steps:
- name: docker
  id: Build
  dir: App
  args: ['build', '.', '-t', 'gcr.io/mta-music-318515/passages:latest']
- name: "docker"
  id: Push
  args: ['push', 'gcr.io/mta-music-318515/passages:latest']
- name: "gcr.io/cloud-builders/kubectl"
  id: Deploy
  dir: App/.kube
  args: ['apply', '--filename=staging.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=production-1'