steps:
- name: gcr.io/cloud-builders/npm
  dir: App
  args: ['run', 'install']
- name: gcr.io/cloud-builders/npm
  dir: App
  args: ['run', 'build']
- name: gcr.io/cloud-builders/gsutil
  dir: App/public
  args: ['-m', 'cp', '*', 'gs://mta-music-passages-staging-app-bucket/']