apiVersion: apps/v1
kind: Deployment
metadata:
  name: passages-production
  labels:
    app: passages
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passages
      provides: production
  template:
    metadata:
      labels:
        app: passages
        provides: production
    spec:
      containers:
      - name: passages
        image: gcr.io/mta-music-318515/passages:production
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        - name: DB_NAME
          value: passages

---

apiVersion: v1
kind: Service
metadata:
  name: passages-production
  labels:
    app: passages
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: passages
    provides: production
