apiVersion: apps/v1
kind: Deployment
metadata:
  name: passages-staging
  labels:
    app: passages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passages
      provides: staging
  template:
    metadata:
      labels:
        app: passages
        provides: staging
    spec:
      containers:
        - name: passages
          image: gcr.io/mta-music-318515/passages:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: DB_NAME
              value: passages

---
apiVersion: v1
kind: Service
metadata:
  name: passages-staging
  labels:
    app: passages
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: passages
    provides: staging
